# Wokwi Configuration File
# Reference: https://docs.wokwi.com/vscode/project-config

[wokwi]
version = 1
firmware = '.pio/build/esp32doit-devkit-v1_20240928_4/firmware.bin'
elf = '.pio/build/esp32doit-devkit-v1_20240928_4/firmware.elf'

[[net]]
ssid = "Wokwi-GUEST"
password = ""

[[chip]]
type = "esp32"

[[components]]
type = "soil-moisture"
pin = 32
name = "Soil Sensor"

[[components]]
type = "button"
pin = 0
name = "Reset Button"

[[components]]
type = "led"
pin = 4
name = "Status LED"

[[components]]
type = "generic"
pin = 26
name = "Pump Relay"
