name: Build & Upload ESP32 Firmware OTA

on:
  push:
    branches: [ master ]

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run -e esp32-prod

      - name: Upload firmware as artifact (optional but recommended)
        uses: actions/upload-artifact@v4
        with:
          name: esp32-prod-${{ github.sha }}.bin
          path: .pio/build/esp32-prod/firmware.bin
          if-no-files-found: error
          retention-days: 7

      - name: Upload firmware to OTA server
        env:
          OTA_UPLOAD_URL: ${{ secrets.OTA_UPLOAD_URL }}   # ← il tuo secret con URL COMPLETO dell’endpoint
        run: |
          if [ -z "${OTA_UPLOAD_URL}" ]; then
            echo "❌ OTA_UPLOAD_URL è vuoto (secret mancante?)"
            exit 1
          fi
          VERSION=$(date +%Y%m%d_%H%M)
          echo "➡️  Upload verso: ${OTA_UPLOAD_URL}"
          echo "➡️  Version: ${VERSION}"
          curl --fail-with-body -sS -m 30 -L \
               -F "file=@.pio/build/esp32-prod/firmware.bin" \
               -F "version=$VERSION" \
               "$OTA_UPLOAD_URL" \
               -w "\nHTTP %{http_code}\n"
